title: Harry Waugh 
github: https://github.com/hw16471
linkedin: https://www.linkedin.com/in/harry-waugh-09a4b1152/
logo: "/assets/img/logo.jpg?raw=true" # your photo (or logo) here
description: >
  <strong> A driven, ambitious and rounded graduate from the University of Bristol, interested in HPC, Computer Graphics and Deep Learning.</strong>
education: Computer Science - University of Bristol (2016-2019)
email: hw16471@my.bristol.ac.uk
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
collections:
  - experiences
  - projects

